### ISSUE TITLE
event-item styling

### ISSUE THREAD

**Issue by Arunkumarupadhyaya** [oOps1627/angular-calendar-timeline#2]
how i customize the style of event-item and panel-header

**Comment by oOps1627** [comment]
Timeline component takes the @input itemContentTemplate for customizing the event-item.
What about panel-header, please describe in more detail what you want to customize

**Comment by Arunkumarupadhyaya** [comment]
but when i change the background color then the default color is showing in background

**Comment by Arunkumarupadhyaya** [comment]
How we can change the default background color in event-item
