### ISSUE TITLE
getFullYear is not a function error

### ISSUE THREAD

**Issue by Caggegi** [oOps1627/angular-calendar-timeline#4]
Using streamItems causes getFullYear is not a function error. That causes the wrong timeline zoom (it sets to 0 and ignores other values)

**Comment by oOps1627** [comment]
Can you show an example array that you pass into the "items" input for reproducing this issue? Or some other specific options. Because I don't have any errors I have no idea why it happened

**Comment by Caggegi** [comment]
Sure, starting from your example:

 items: ITimelineItem[] = [{
      id: 6,
      name: "Stream",
      childrenItems: [
        {
          startDate: new Date("2023-10-02T00:00:00"),
          endDate: new Date("2023-10-05T00:00:00"),
          id: 7,
          name: "Child of stream",
          canResizeLeft: true,
          canResizeRight: true,
          canDragX: true
        }
      ],
      streamItems: [
        {
          startDate: new Date("2023-10-02T00:00:00"),
          endDate: new Date("2023-10-02T10:00:00"),
          id: 8,
          name: "Stream 1",
          canResizeLeft: true,
          canResizeRight: true,
          canDragX: true
        },
        {
          startDate: new Date("2023-10-04T00:00:00"),
          endDate: new Date("2023-10-05T00:00:00"),
          id: 9,
          name: "Stream 2",
          canResizeLeft: true,
          canResizeRight: true,
          canDragX: true
        },
        {
          startDate: new Date("2023-09-26T00:00:00"),
          endDate: new Date("2023-09-29T00:00:00"),
          id: 10,
          name: "Stream 3",
          canResizeLeft: true,
          canResizeRight: true,
          canDragX: true
        }
      ]
    }]

the issue will no longer exists if we add before (for example) the object:
{
      startDate: new Date("2023-09-30T00:00:00"),
      endDate: new Date("2023-09-30T10:00:00"),
      id: 1,
      name: "Routine 1",
      canResizeLeft: false,
      canResizeRight: false,
      canDragX: false
    }

**Comment by oOps1627** [comment]
@Caggegi  Thanks, seems I have found the problem. I published a new update with a fix. Can you please try the new version (0.4.2) and check it? And also could you say what version of Angular you use?

**Comment by Caggegi** [comment]
It seems all is working fine now, thank you for your time!!

- Angular CLI version 13.3.8
